#!/bin/sh


SUBMISSION_PATH=$1;
CODE_PATH=$2;
CODE=$3;
BUILDING_SCRIPT_PATH=$4;
BUILDING_SCRIPT=$5;


mkdir $SUBMISSION_PATH;
touch $CODE_PATH;
touch $BUILDING_SCRIPT_PATH;
echo $CODE > $CODE_PATH;
echo -e '"${BUILDING_SCRIPT}"' >> $BUILDING_SCRIPT_PATH;